apiVersion: cozystack.io/v1alpha1
kind: ApplicationDefinition
metadata:
  name: wordpress
spec:
  application:
    kind: Wordpress
    singular: wordpress
    plural: wordpresses
    openAPISchema: '{"title":"Chart Values","type":"object","properties":{"host":{"type":"string","description":"Hostname for WordPress"},"replicas":{"type":"integer","default":1,"description":"Number of replicas"},"password":{"type":"string","description":"WordPress admin password"}}}'
  release:
    chartRef:
      kind: HelmChart
      name: external-apps-wordpress
      namespace: cozy-public
    labels:
      cozystack.io/ui: "true"
    prefix: wordpress-
  dashboard:
    category: PaaS
    singular: WordPress
    plural: WordPresses
    description: Managed WordPress service
    tags:
      - cms
      - php
    icon: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iIzIxNzU5YiI+CiAgPHBhdGggZD0iTTEyIDJDNi40ODYgMiAyIDYuNDg2IDIgMTJzNC40ODYgMTAgMTAgMTAgMTAtNC40ODYgMTAtMTBTMTcuNTE0IDIgMTIgMnptMCAxOS41QzYuNzYgMjEuNSAyLjUgMTcuMjQgMi41IDEyUzYuNzYgMi41IDEyIDIuNSAyMS41IDYuNzYgMjEuNSAxMiAxNy4yNCAyMS41IDEyIDIxLjV6bS0xLTE0LjVsLTMgOWgxLjVsLjc1LTIuMjVoMS41TDEyLjUgMTdoMS41bC0zLTl6bTMuNSAwbDIgNiAyLTZoLTEuNWwtMSAzLTEtM3oiLz4KPC9zdmc+Cg==
