apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: external-apps-wordpress
  namespace: cozy-public
spec:
  interval: 5m
  chart: ./packages/apps/wordpress
  sourceRef:
    kind: GitRepository
    name: external-apps
    namespace: cozy-public
  reconcileStrategy: Revision
